// File generated by the FlutterFire CLI — DO NOT hand-edit in production.
//
// This is a **placeholder**. Run the following from the project root to
// generate the real file with your Firebase project's credentials:
//
//   dart pub global activate flutterfire_cli
//   flutterfire configure
//
// That command overwrites this file with real `appId`, `apiKey`, and
// `projectId` values for each platform you select (iOS, Android, Web).
// See docs/FIREBASE_SETUP.md for the full walkthrough.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform. '
          'Run `flutterfire configure` to generate platform-specific options.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REPLACE_WITH_WEB_API_KEY',
    appId: 'REPLACE_WITH_WEB_APP_ID',
    messagingSenderId: 'REPLACE_WITH_SENDER_ID',
    projectId: 'nexagram-app',
    authDomain: 'nexagram-app.firebaseapp.com',
    storageBucket: 'nexagram-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REPLACE_WITH_ANDROID_API_KEY',
    appId: 'REPLACE_WITH_ANDROID_APP_ID',
    messagingSenderId: 'REPLACE_WITH_SENDER_ID',
    projectId: 'nexagram-app',
    storageBucket: 'nexagram-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_WITH_IOS_API_KEY',
    appId: 'REPLACE_WITH_IOS_APP_ID',
    messagingSenderId: 'REPLACE_WITH_SENDER_ID',
    projectId: 'nexagram-app',
    storageBucket: 'nexagram-app.appspot.com',
    iosBundleId: 'com.nexagram.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'REPLACE_WITH_MACOS_API_KEY',
    appId: 'REPLACE_WITH_MACOS_APP_ID',
    messagingSenderId: 'REPLACE_WITH_SENDER_ID',
    projectId: 'nexagram-app',
    storageBucket: 'nexagram-app.appspot.com',
    iosBundleId: 'com.nexagram.app',
  );
}
